# Generated by Django 3.0.2 on 2020-01-04 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0002_auto_20200104_1923'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время конца')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тренировочный день',
                'verbose_name_plural': 'Тренировочные дни',
            },
        ),
        migrations.CreateModel(
            name='TrainingDayRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('attempts', models.SmallIntegerField()),
                ('result', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='training.TrainingDay')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='route.Route')),
            ],
            options={
                'verbose_name': 'Трасса с тренировки',
                'verbose_name_plural': 'Трассы с тренировки',
            },
        ),
    ]
