# Generated by Django 3.0.2 on 2020-01-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20200104_1923'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdayroute',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.TrainingDay'),
        ),
        migrations.AlterField(
            model_name='trainingdayroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='route.Route'),
        ),
    ]
