# Generated by Django 3.0.2 on 2020-01-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('climbingwall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=10)),
                ('base_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('url', models.URLField()),
                ('climbingwall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='climbingwall.Climbingwall')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='social_networks.SocialNetwork')),
            ],
            options={
                'verbose_name': 'Ссылка социальной сети',
                'verbose_name_plural': 'Ссылки социальной сети',
            },
        ),
    ]
